-- PostgreSQL proposal; not executed by localhost prototype.
CREATE TABLE career_profiles(id UUID PRIMARY KEY,owner_id UUID,mode TEXT NOT NULL CHECK(mode IN('worker','explorer')),stage TEXT CHECK(stage IS NULL OR stage IN('middle','high','university','jobseeker')),consent_version TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE diagnoses(id UUID PRIMARY KEY,profile_id UUID NOT NULL REFERENCES career_profiles(id) ON DELETE CASCADE,model_version TEXT NOT NULL,base_year INTEGER,input_snapshot JSONB NOT NULL,result_snapshot JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE activity_submissions(id UUID PRIMARY KEY,profile_id UUID NOT NULL REFERENCES career_profiles(id) ON DELETE CASCADE,activity_id TEXT NOT NULL,revision INTEGER NOT NULL DEFAULT 1,draft TEXT,reflection JSONB,status TEXT NOT NULL CHECK(status IN('draft','completed')),updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),UNIQUE(profile_id,activity_id));
CREATE TABLE journal_entries(id UUID PRIMARY KEY,profile_id UUID NOT NULL REFERENCES career_profiles(id) ON DELETE CASCADE,occupation_id TEXT,task_id TEXT,activity_id TEXT,mode TEXT NOT NULL CHECK(mode IN('worker','explorer')),minutes NUMERIC CHECK(minutes>=0),verification_minutes NUMERIC CHECK(verification_minutes>=0),reflection TEXT,result_notes TEXT,next_action TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE goals(id UUID PRIMARY KEY,profile_id UUID NOT NULL REFERENCES career_profiles(id) ON DELETE CASCADE,title TEXT NOT NULL,check_at TIMESTAMPTZ,completed BOOLEAN NOT NULL DEFAULT false,revision INTEGER NOT NULL DEFAULT 1);
CREATE TABLE published_updates(id UUID PRIMARY KEY,title TEXT NOT NULL,source_url TEXT,published_at TIMESTAMPTZ,checked_at TIMESTAMPTZ,review_status TEXT NOT NULL,related_task_ids JSONB NOT NULL,payload JSONB NOT NULL);
CREATE TABLE notification_preferences(profile_id UUID PRIMARY KEY REFERENCES career_profiles(id) ON DELETE CASCADE,enabled BOOLEAN NOT NULL DEFAULT false,channel TEXT,frequency TEXT,categories JSONB NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE monthly_reports(id UUID PRIMARY KEY,profile_id UUID NOT NULL REFERENCES career_profiles(id) ON DELETE CASCADE,period_start DATE NOT NULL,period_end DATE NOT NULL,snapshot JSONB NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE share_grants(id UUID PRIMARY KEY,diagnosis_id UUID NOT NULL REFERENCES diagnoses(id) ON DELETE CASCADE,token_hash TEXT NOT NULL UNIQUE,selected_sections JSONB NOT NULL,expires_at TIMESTAMPTZ NOT NULL,revoked_at TIMESTAMPTZ);
CREATE TABLE content_reviews(id UUID PRIMARY KEY,entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,version TEXT NOT NULL,review_status TEXT NOT NULL,reviewer_id UUID,reviewed_at TIMESTAMPTZ,payload JSONB NOT NULL,rationale TEXT);
CREATE INDEX diagnoses_profile_created ON diagnoses(profile_id,created_at DESC);
-- Implementation must add master ID foreign keys, accounts/auth, ownership rules,
-- version releases/audit tables and notification consent audit before production.
